---
- hosts: inv_1
  become: yes
  vars:
    - homeDir: /home/ubuntu
    - appDir: applications
    - repo: simp_serv
    - account: dnahid
    - privateKey: /Users/nahid/.ssh/id_rsa

  tasks:
    - name: Install necessary packages
      apt:
        name: ["build-essential", "nodejs", "git", "curl"]

    - name: Install pm2 to run node application
      npm: name=pm2 global=yes production=yes

    - name: Create APP Directory
      file: path={{homeDir}}/{{appDir}} state=directory

    - name: Copy Private Key
      copy: src={{privateKey}} dest={{homeDir}} mode=0600

    - name: Git Clone Repo
      git: repo=git@github.com:{{account}}/{{repo}}.git dest={{homeDir}}/{{appDir}} update=yes force=yes accept_hostkey=yes key_file={{homeDir}}/id_rsa version=app-on-vm
      register: git_finished

    - name: Running NPM install
      npm: path={{homeDir}}/{{appDir}}
      register: npm_finished
      when: git_finished is succeeded

    - name: Stop APP
      become: true
      become_user: nahid
      command: pm2 stop simp_serv chdir={{homeDir}}/{{appDir}}/src
      ignore_errors: yes

    - name: Start APP
      become: true
      become_user: nahid
      command: pm2 start index.js --name simp_serv chdir={{homeDir}}/{{appDir}}/src
      ignore_errors: yes
      when: npm_finished is succeeded
