---
- hosts: production
  remote_user: nahid
  become: yes
  become_method: sudo
  tasks:
    - name: Install pip3 in the server
      apt: name=python3-pip state=present
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
    - name: install docker in the server
      pip:
        name: docker
        executable: pip3
    - name: install docker compose in the server
      pip:
        name: docker-compose
        executable: pip3
    - name: Generate docker image from dockerfile
      docker_image:
        name: nodeapp
        path: .
        state: build

    - name: Run the application container
      docker_container:
        image: nodeapp:latest
        path: .
        state: running
